version: '3.1'

services:
  prod-zabbix-app-phpmyadmin:
    image: phpmyadmin
    container_name: "prod-zabbix-app-phpmyadmin"
    restart: always
    ports:
      - 58081:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT="300M"

networks:
  default:
    external: true
    name: bridge_backend
